name: Get Latest Build Run ID
description: Gets the latest successful build.yml workflow run ID, or uses provided run_id

inputs:
  run_id:
    description: 'Build workflow run ID (leave empty to use latest)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token with actions:read permission'
    required: true

outputs:
  run_id:
    description: 'The build workflow run ID to use'
    value: ${{ steps.determine-run-id.outputs.run_id }}

runs:
  using: composite
  steps:
    - name: Get Latest Build Run ID
      if: inputs.run_id == ''
      id: get-run-id
      shell: bash
      run: |
        RUN_ID=$(gh run list --workflow=build.yml --status=success --limit=1 --json databaseId --jq '.[0].databaseId')
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        echo "Using build run ID: $RUN_ID"
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Use Provided Run ID
      if: inputs.run_id != ''
      id: use-provided-run-id
      shell: bash
      run: |
        echo "run_id=${{ inputs.run_id }}" >> $GITHUB_OUTPUT
        echo "Using provided build run ID: ${{ inputs.run_id }}"

    - name: Determine Run ID
      id: determine-run-id
      shell: bash
      run: |
        if [ -n "${{ inputs.run_id }}" ]; then
          echo "run_id=${{ inputs.run_id }}" >> $GITHUB_OUTPUT
        else
          echo "run_id=${{ steps.get-run-id.outputs.run_id }}" >> $GITHUB_OUTPUT
        fi
