name: Build and Upload NuGet Package
description: Builds a NuGet package and uploads it as an artifact

inputs:
  project-path:
    description: 'Path to the project file'
    required: true
  version:
    description: 'Version number for the package'
    required: true
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true
  retention-days:
    description: 'Number of days to retain the artifact'
    required: false
    default: '1'
  prerelease:
    description: 'Whether the package is a prerelease version'
    required: false
    default: 'false'
  registry-name:
    description: 'NuGet registry name'
    required: false
    default: 'nuget.org'
  registry-uri:
    description: 'NuGet registry URI'
    required: false
    default: 'https://api.nuget.org/v3/index.json'

runs:
  using: composite
  steps:
    - name: Add or Update NuGet Source
      shell: pwsh
      env:
        REGISTRY_NAME: ${{ inputs.registry-name }}
        REGISTRY_URI: ${{ inputs.registry-uri }}
      run: |
        [string]$Sources = dotnet nuget list source
        if (!($Sources -imatch "\d*\. $env:REGISTRY_NAME")) {
          dotnet nuget add source --name "$env:REGISTRY_NAME" "$env:REGISTRY_URI"
        }
        else {
          Write-Host "Source exists. Updating."
          dotnet nuget update source "$env:REGISTRY_NAME" --source "$env:REGISTRY_URI"
        }

    - name: Build NuGet Package (Prerelease)
      if: ${{ inputs.prerelease == 'true' }}
      shell: pwsh
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        VERSION: ${{ inputs.version }}
      run: |
        Write-Host "Building $env:PROJECT_PATH with version $env:VERSION (Prerelease)"
        dotnet build $env:PROJECT_PATH -c Release -p:FileVersion="$env:VERSION" -p:AssemblyVersion="$env:VERSION" -p:VersionPrefix="$env:VERSION" -p:VersionSuffix="dev"

    - name: Build NuGet Package (Release)
      if: ${{ inputs.prerelease != 'true' }}
      shell: pwsh
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        VERSION: ${{ inputs.version }}
      run: |
        Write-Host "Building $env:PROJECT_PATH with version $env:VERSION (Release)"
        dotnet build $env:PROJECT_PATH -c Release -p:FileVersion="$env:VERSION" -p:AssemblyVersion="$env:VERSION" -p:VersionPrefix="$env:VERSION"

    - name: Find NuGet Package
      id: find-nupkg
      shell: pwsh
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
      run: |
        $projectDir = Split-Path -Parent "$env:PROJECT_PATH"
        $searchDir = Join-Path $projectDir "bin\Release"
        Write-Host "Searching for nupkg in $searchDir"
        
        if (!(Test-Path $searchDir)) {
          Write-Error "Directory $searchDir not found"
          exit 1
        }
        
        $pkg = Get-ChildItem -Path $searchDir -Filter '*.nupkg' -File | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        
        if (-not $pkg) {
          Write-Error "NuGet package not found in $searchDir"
          exit 1
        }
        
        Write-Host "Found package: $($pkg.FullName)"
        echo "NUPKG_PATH=$($pkg.FullName)" >> $env:GITHUB_OUTPUT

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.find-nupkg.outputs.NUPKG_PATH }}
        retention-days: ${{ inputs.retention-days }}
