name: Build and Upload NuGet Package
description: Builds a NuGet package and uploads it as an artifact

inputs:
  project-path:
    description: 'Path to the project file'
    required: true
  version:
    description: 'Version number for the package'
    required: true
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true
  retention-days:
    description: 'Number of days to retain the artifact'
    required: false
    default: '1'
  prerelease:
    description: 'Whether the package is a prerelease version'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Build NuGet Package
      shell: pwsh
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        VERSION: ${{ inputs.version }}
      run: |
        $PackageVersion = $env:VERSION
        if ("${{ inputs.prerelease }}" -eq "true") {
          $PackageVersion += "-dev"
        }
        Write-Host "Building $env:PROJECT_PATH with version $env:VERSION (Prerelease)"
        dotnet build $env:PROJECT_PATH -c Release -p:FileVersion="$env:VERSION" -p:AssemblyVersion="$env:VERSION" -p:PackageVersion="$PackageVersion"

    - name: Find NuGet Package
      id: find-nupkg
      shell: pwsh
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
      run: |
        $projectDir = Split-Path -Parent "$env:PROJECT_PATH"
        $searchDir = Join-Path $projectDir "bin\Release"
        Write-Host "Searching for nupkg in $searchDir"
        
        if (!(Test-Path $searchDir)) {
          Write-Error "Directory $searchDir not found"
          exit 1
        }
        
        $pkg = Get-ChildItem -Path $searchDir -Filter '*.nupkg' -File | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        
        if (-not $pkg) {
          Write-Error "NuGet package not found in $searchDir"
          exit 1
        }
        
        Write-Host "Found package: $($pkg.FullName)"
        echo "NUPKG_PATH=$($pkg.FullName)" >> $env:GITHUB_OUTPUT

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.find-nupkg.outputs.NUPKG_PATH }}
        retention-days: ${{ inputs.retention-days }}
