// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.AgentUpdate.GetHashSha256
{
    /// <summary>
    /// Builds and executes requests for operations under \api\agent-update\get-hash-sha256
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetHashSha256RequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ControlR.ApiClient.api.agentUpdate.getHashSha256.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.Item.WithRuntimeItemRequestBuilder"/></returns>
        public global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.Item.WithRuntimeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("runtime", position);
                return new global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.Item.WithRuntimeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.GetHashSha256RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetHashSha256RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/agent-update/get-hash-sha256", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.GetHashSha256RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetHashSha256RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/agent-update/get-hash-sha256", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
