# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  controlr:
    build:
      context: "C:\\Repos\\ControlR"
      dockerfile: "ControlR.Web.Server/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/ControlR.Web.Server.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "controlrwebserver:dev"
    ports:
    - "127.0.0.1:57820:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\trans\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Repos\\ControlR\\ControlR.Web.Server:/app:rw"
    - "C:\\Repos\\ControlR:/src:rw"
    - "C:\\Users\\trans\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.4\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\trans\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_21_10_12_06:/var/opt/rider-debugger:rw"
    working_dir: "/app"
