// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.UserServerSettings.FileUploadMaxSize;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.UserServerSettings
{
    /// <summary>
    /// Builds and executes requests for operations under \api\user-server-settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserServerSettingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fileUploadMaxSize property</summary>
        public global::ControlR.ApiClient.Api.UserServerSettings.FileUploadMaxSize.FileUploadMaxSizeRequestBuilder FileUploadMaxSize
        {
            get => new global::ControlR.ApiClient.Api.UserServerSettings.FileUploadMaxSize.FileUploadMaxSizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.UserServerSettings.UserServerSettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserServerSettingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user-server-settings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.UserServerSettings.UserServerSettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserServerSettingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user-server-settings", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
