// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.DeviceFileSystem.Contents;
using ControlR.ApiClient.Api.DeviceFileSystem.PathSegments;
using ControlR.ApiClient.Api.DeviceFileSystem.RootDrives;
using ControlR.ApiClient.Api.DeviceFileSystem.Subdirectories;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.DeviceFileSystem
{
    /// <summary>
    /// Builds and executes requests for operations under \api\device-file-system
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceFileSystemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The contents property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileSystem.Contents.ContentsRequestBuilder Contents
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileSystem.Contents.ContentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pathSegments property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileSystem.PathSegments.PathSegmentsRequestBuilder PathSegments
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileSystem.PathSegments.PathSegmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rootDrives property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileSystem.RootDrives.RootDrivesRequestBuilder RootDrives
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileSystem.RootDrives.RootDrivesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subdirectories property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileSystem.Subdirectories.SubdirectoriesRequestBuilder Subdirectories
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileSystem.Subdirectories.SubdirectoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.DeviceFileSystem.DeviceFileSystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceFileSystemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device-file-system", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.DeviceFileSystem.DeviceFileSystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceFileSystemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device-file-system", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
