// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.DeviceFileOperations.CreateDirectory;
using ControlR.ApiClient.Api.DeviceFileOperations.Delete;
using ControlR.ApiClient.Api.DeviceFileOperations.Download;
using ControlR.ApiClient.Api.DeviceFileOperations.Upload;
using ControlR.ApiClient.Api.DeviceFileOperations.ValidatePath;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.DeviceFileOperations
{
    /// <summary>
    /// Builds and executes requests for operations under \api\device-file-operations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceFileOperationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The createDirectory property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileOperations.CreateDirectory.CreateDirectoryRequestBuilder CreateDirectory
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileOperations.CreateDirectory.CreateDirectoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileOperations.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileOperations.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileOperations.Download.DownloadRequestBuilder Download
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileOperations.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileOperations.Upload.UploadRequestBuilder Upload
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileOperations.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validatePath property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileOperations.ValidatePath.ValidatePathRequestBuilder ValidatePath
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileOperations.ValidatePath.ValidatePathRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.DeviceFileOperations.DeviceFileOperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceFileOperationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device-file-operations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.DeviceFileOperations.DeviceFileOperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceFileOperationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/device-file-operations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
