<Project Sdk="Aspire.AppHost.Sdk/13.5.4">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsAspireHost>true</IsAspireHost>
     <AspireUseCliBundle>true</AspireUseCliBundle>
		<UserSecretsId>81fccb1a-eb24-4545-a8ac-430f71e5178b</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
		<PackageReference Update="Bitbound.Analyzers.MemberOrder">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ControlR.Agent\ControlR.Agent.csproj" />
		<ProjectReference Include="..\ControlR.DesktopClient\ControlR.DesktopClient.csproj" />
		<ProjectReference Include="..\ControlR.Web.Server\ControlR.Web.Server.csproj" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ControlR.Web.ServiceDefaults\ControlR.Web.ServiceDefaults.csproj" IsAspireProjectResource="false" />
	</ItemGroup>
</Project>