// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.InstallerKeys.IncrementUsage;
using ControlR.ApiClient.Api.InstallerKeys.Item;
using ControlR.ApiClient.Api.InstallerKeys.Rename;
using ControlR.ApiClient.Api.InstallerKeys.Usages;
using ControlR.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ControlR.ApiClient.Api.InstallerKeys
{
    /// <summary>
    /// Builds and executes requests for operations under \api\installer-keys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstallerKeysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The incrementUsage property</summary>
        public global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.IncrementUsageRequestBuilder IncrementUsage
        {
            get => new global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.IncrementUsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rename property</summary>
        public global::ControlR.ApiClient.Api.InstallerKeys.Rename.RenameRequestBuilder Rename
        {
            get => new global::ControlR.ApiClient.Api.InstallerKeys.Rename.RenameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usages property</summary>
        public global::ControlR.ApiClient.Api.InstallerKeys.Usages.UsagesRequestBuilder Usages
        {
            get => new global::ControlR.ApiClient.Api.InstallerKeys.Usages.UsagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ControlR.ApiClient.api.installerKeys.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.InstallerKeys.Item.InstallerKeysItemRequestBuilder"/></returns>
        public global::ControlR.ApiClient.Api.InstallerKeys.Item.InstallerKeysItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ControlR.ApiClient.Api.InstallerKeys.Item.InstallerKeysItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ControlR.ApiClient.api.installerKeys.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.InstallerKeys.Item.InstallerKeysItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ControlR.ApiClient.Api.InstallerKeys.Item.InstallerKeysItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::ControlR.ApiClient.Api.InstallerKeys.Item.InstallerKeysItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstallerKeysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/installer-keys", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstallerKeysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/installer-keys", rawUrl)
        {
        }
        /// <returns>A List&lt;global::ControlR.ApiClient.Models.AgentInstallerKeyDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ControlR.ApiClient.Models.AgentInstallerKeyDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ControlR.ApiClient.Models.AgentInstallerKeyDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ControlR.ApiClient.Models.AgentInstallerKeyDto>(requestInfo, global::ControlR.ApiClient.Models.AgentInstallerKeyDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.CreateInstallerKeyResponseDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ControlR.ApiClient.Models.CreateInstallerKeyResponseDto?> PostAsync(global::ControlR.ApiClient.Models.CreateInstallerKeyRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ControlR.ApiClient.Models.CreateInstallerKeyResponseDto> PostAsync(global::ControlR.ApiClient.Models.CreateInstallerKeyRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::ControlR.ApiClient.Models.CreateInstallerKeyResponseDto>(requestInfo, global::ControlR.ApiClient.Models.CreateInstallerKeyResponseDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ControlR.ApiClient.Models.CreateInstallerKeyRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ControlR.ApiClient.Models.CreateInstallerKeyRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InstallerKeysRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InstallerKeysRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
