// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.ServerLogs.GetAspireUrl;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.ServerLogs
{
    /// <summary>
    /// Builds and executes requests for operations under \api\server-logs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServerLogsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getAspireUrl property</summary>
        public global::ControlR.ApiClient.Api.ServerLogs.GetAspireUrl.GetAspireUrlRequestBuilder GetAspireUrl
        {
            get => new global::ControlR.ApiClient.Api.ServerLogs.GetAspireUrl.GetAspireUrlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ServerLogs.ServerLogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServerLogsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/server-logs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ServerLogs.ServerLogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServerLogsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/server-logs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
