// <auto-generated />
using System;
using ControlR.Web.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlR.Web.Server.Data.Migrations
{
  [DbContext(typeof(AppDb))]
  [Migration("20260912020000_RemoveOrphanedServerAlertsReadGrants")]
  partial class RemoveOrphanedServerAlertsReadGrants
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.9")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AgentInstallerKey", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<long?>("AllowedUses")
                      .HasColumnType("bigint");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<Guid>("CreatorId")
                      .HasColumnType("uuid");

            b.Property<int>("CreatorKind")
                      .HasColumnType("integer");

            b.Property<DateTimeOffset?>("Expiration")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("FriendlyName")
                      .HasMaxLength(200)
                      .HasColumnType("character varying(200)");

            b.Property<string>("HashedKey")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<int>("KeyType")
                      .HasColumnType("integer");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("TenantId");

            b.ToTable("AgentInstallerKeys");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AgentInstallerKeyUsage", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<Guid>("AgentInstallerKeyId")
                      .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<Guid>("DeviceId")
                      .HasColumnType("uuid");

            b.Property<string>("RemoteIpAddress")
                      .HasColumnType("text");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("AgentInstallerKeyId");

            b.HasIndex("TenantId");

            b.ToTable("AgentInstallerKeyUsages");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AppUser", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid");

            b.Property<int>("AccessFailedCount")
                      .HasColumnType("integer");

            b.Property<string>("AccountType")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<string>("ConcurrencyStamp")
                      .IsConcurrencyToken()
                      .HasColumnType("text");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Email")
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<bool>("EmailConfirmed")
                      .HasColumnType("boolean");

            b.Property<bool>("IsOnline")
                      .HasColumnType("boolean");

            b.Property<DateTimeOffset?>("LastLogin")
                      .HasColumnType("timestamp with time zone");

            b.Property<bool>("LockoutEnabled")
                      .HasColumnType("boolean");

            b.Property<DateTimeOffset?>("LockoutEnd")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("NormalizedEmail")
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<string>("NormalizedUserName")
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<string>("PasswordHash")
                      .HasColumnType("text");

            b.Property<string>("PhoneNumber")
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<bool>("PhoneNumberConfirmed")
                      .HasColumnType("boolean");

            b.Property<bool>("RequirePasswordChange")
                      .HasColumnType("boolean");

            b.Property<string>("SecurityStamp")
                      .HasColumnType("text");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.Property<bool>("TwoFactorEnabled")
                      .HasColumnType("boolean");

            b.Property<string>("UserName")
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.HasKey("Id");

            b.HasIndex("NormalizedEmail")
                      .HasDatabaseName("EmailIndex");

            b.HasIndex("NormalizedUserName")
                      .IsUnique()
                      .HasDatabaseName("UserNameIndex");

            b.HasIndex("TenantId");

            b.ToTable("AspNetUsers", (string)null);
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AuthorizationChangeLog", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("ActionType")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid?>("ActorPrincipalId")
                      .HasColumnType("uuid");

            b.Property<string>("ActorPrincipalType")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<string>("AfterJson")
                      .HasColumnType("text");

            b.Property<string>("BeforeJson")
                      .HasColumnType("text");

            b.Property<string>("CorrelationId")
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("IpAddress")
                      .HasMaxLength(64)
                      .HasColumnType("character varying(64)");

            b.Property<Guid?>("OwningTenantId")
                      .HasColumnType("uuid");

            b.Property<Guid?>("TargetId")
                      .HasColumnType("uuid");

            b.Property<string>("TargetType")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.HasKey("Id");

            b.HasIndex("ActorPrincipalId");

            b.HasIndex("CreatedAt");

            b.HasIndex("OwningTenantId");

            b.HasIndex("TargetId");

            b.ToTable("AuthorizationChangeLogs");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Customer", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Description")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<string>("Notes")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("TenantId", "Name")
                      .IsUnique();

            b.ToTable("Customers");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Device", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AgentVersion")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<string>("Alias")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<string>("ConnectionId")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<double>("CpuUtilization")
                      .HasColumnType("double precision");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.PrimitiveCollection<string[]>("CurrentUsers")
                      .IsRequired()
                      .HasColumnType("text[]");

            b.Property<Guid?>("CustomerId")
                      .HasColumnType("uuid");

            b.Property<Guid?>("DeviceGroupId")
                      .HasColumnType("uuid");

            b.Property<string>("DnsHostName")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("character varying(255)");

            b.Property<bool>("Is64Bit")
                      .HasColumnType("boolean");

            b.Property<bool>("IsOnline")
                      .HasColumnType("boolean");

            b.Property<DateTimeOffset>("LastSeen")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("LocalIpV4")
                      .IsRequired()
                      .HasMaxLength(15)
                      .HasColumnType("character varying(15)");

            b.Property<string>("LocalIpV6")
                      .IsRequired()
                      .HasMaxLength(39)
                      .HasColumnType("character varying(39)");

            b.PrimitiveCollection<string[]>("MacAddresses")
                      .IsRequired()
                      .HasColumnType("text[]");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<int>("OsArchitecture")
                      .HasColumnType("integer");

            b.Property<string>("OsDescription")
                      .IsRequired()
                      .HasMaxLength(300)
                      .HasColumnType("character varying(300)");

            b.Property<int>("Platform")
                      .HasColumnType("integer");

            b.Property<int>("ProcessorCount")
                      .HasColumnType("integer");

            b.Property<string>("PublicIpV4")
                      .IsRequired()
                      .HasMaxLength(15)
                      .HasColumnType("character varying(15)");

            b.Property<string>("PublicIpV6")
                      .IsRequired()
                      .HasMaxLength(39)
                      .HasColumnType("character varying(39)");

            b.Property<string>("PublicKey")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.Property<double>("TotalMemory")
                      .HasColumnType("double precision");

            b.Property<double>("TotalStorage")
                      .HasColumnType("double precision");

            b.Property<double>("UsedMemory")
                      .HasColumnType("double precision");

            b.Property<double>("UsedStorage")
                      .HasColumnType("double precision");

            b.HasKey("Id");

            b.HasIndex("CustomerId");

            b.HasIndex("TenantId");

            b.ToTable("Devices");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.DeviceGroup", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Description")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("TenantId", "Name")
                      .IsUnique();

            b.ToTable("DeviceGroups");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.DeviceGroupMember", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<Guid>("DeviceGroupId")
                      .HasColumnType("uuid");

            b.Property<Guid>("DeviceId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("DeviceId");

            b.HasIndex("DeviceGroupId", "DeviceId")
                      .IsUnique();

            b.ToTable("DeviceGroupMembers");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.LogonToken", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AllowedDesktopSessionIds")
                      .HasColumnType("jsonb");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<Guid>("DeviceId")
                      .HasColumnType("uuid");

            b.Property<DateTimeOffset>("ExpiresAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<bool>("IsConsumed")
                      .HasColumnType("boolean");

            b.Property<string>("Prefix")
                      .HasMaxLength(32)
                      .HasColumnType("character varying(32)");

            b.Property<string>("SessionCorrelationId")
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.Property<string>("Token")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<string>("UserCorrelationId")
                      .HasMaxLength(252)
                      .HasColumnType("character varying(252)");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("DeviceId");

            b.HasIndex("TenantId");

            b.HasIndex("Token")
                      .IsUnique();

            b.HasIndex("UserId");

            b.ToTable("LogonTokens");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.PermissionAssignment", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("CreatedByPrincipalId")
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<string>("CreatedByPrincipalType")
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<string>("Effect")
                      .IsRequired()
                      .HasMaxLength(20)
                      .HasColumnType("character varying(20)");

            b.Property<bool>("IsEnabled")
                      .HasColumnType("boolean");

            b.Property<string>("Notes")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<Guid?>("OwningTenantId")
                      .HasColumnType("uuid");

            b.Property<string>("PermissionName")
                      .IsRequired()
                      .HasMaxLength(150)
                      .HasColumnType("character varying(150)");

            b.Property<Guid>("PrincipalId")
                      .HasColumnType("uuid");

            b.Property<string>("PrincipalKind")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<Guid?>("ScopeId")
                      .HasColumnType("uuid");

            b.Property<string>("ScopeKind")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.HasKey("Id");

            b.HasIndex("PrincipalKind", "PrincipalId");

            b.HasIndex("ScopeKind", "ScopeId");

            b.HasIndex("PrincipalKind", "PrincipalId", "PermissionName", "ScopeKind", "ScopeId", "Effect")
                      .IsUnique();

            NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PrincipalKind", "PrincipalId", "PermissionName", "ScopeKind", "ScopeId", "Effect"), false);

            b.ToTable("PermissionAssignments", t =>
                      {
                    t.HasCheckConstraint("CA_PermissionAssignments_NonServer_OwningTenant", "\"ScopeKind\" IN ('Unknown', 'Server') OR \"OwningTenantId\" IS NOT NULL");

                    t.HasCheckConstraint("CA_PermissionAssignments_ScopeKind_ScopeId", "\"ScopeKind\" NOT IN ('Tenant', 'Device', 'DeviceGroup', 'CustomerTenant', 'UserGroup') OR \"ScopeId\" IS NOT NULL");

                    t.HasCheckConstraint("CA_PermissionAssignments_Server_NullScope", "\"ScopeKind\" <> 'Server' OR (\"ScopeId\" IS NULL AND \"OwningTenantId\" IS NULL)");
                  });
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.PersonalAccessToken", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<Guid?>("CreatedByUserId")
                      .HasColumnType("uuid");

            b.Property<DateTimeOffset?>("ExpiresAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("HashedKey")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<DateTimeOffset?>("LastUsed")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<string>("PermissionMode")
                      .IsRequired()
                      .ValueGeneratedOnAdd()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)")
                      .HasDefaultValue("Restricted");

            b.Property<DateTimeOffset?>("RevokedAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("HashedKey")
                      .IsUnique();

            b.HasIndex("UserId");

            b.ToTable("PersonalAccessTokens");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.ServerAlert", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<bool>("IsDismissable")
                      .HasColumnType("boolean");

            b.Property<bool>("IsEnabled")
                      .HasColumnType("boolean");

            b.Property<bool>("IsSticky")
                      .HasColumnType("boolean");

            b.Property<string>("Message")
                      .IsRequired()
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<int>("Severity")
                      .HasColumnType("integer");

            b.HasKey("Id");

            b.ToTable("ServerAlerts");

            b.HasData(
                      new
                  {
                    Id = new Guid("00000000-0000-0000-0000-000000000001"),
                    CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                    IsDismissable = true,
                    IsEnabled = false,
                    IsSticky = false,
                    Message = "",
                    Severity = 0
                  });
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.ServiceAccount", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AccessMode")
                      .IsRequired()
                      .ValueGeneratedOnAdd()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)")
                      .HasDefaultValue("Restricted");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Description")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<bool>("IsEnabled")
                      .HasColumnType("boolean");

            b.Property<string>("Kind")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid?>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("Name")
                      .IsUnique()
                      .HasDatabaseName("IX_ServiceAccounts_Server_Name")
                      .HasFilter("\"Kind\" = 'Server' AND \"TenantId\" IS NULL");

            b.HasIndex("TenantId", "Name")
                      .IsUnique()
                      .HasDatabaseName("IX_ServiceAccounts_TenantId_Name")
                      .HasFilter("\"Kind\" = 'Tenant' AND \"TenantId\" IS NOT NULL");

            b.ToTable("ServiceAccounts", t =>
                      {
                    t.HasCheckConstraint("CK_ServiceAccounts_Kind_TenantId", "(\"Kind\" = 'Server' AND \"TenantId\" IS NULL) OR (\"Kind\" = 'Tenant' AND \"TenantId\" IS NOT NULL)");
                  });
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.ServiceAccountCredential", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<DateTimeOffset?>("ExpiresAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("HashedSecret")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<DateTimeOffset?>("LastUsedAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<DateTimeOffset?>("RevokedAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<Guid>("ServiceAccountId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ServiceAccountId");

            b.ToTable("ServiceAccountCredentials");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Tag", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.Property<int>("Type")
                      .HasColumnType("integer");

            b.HasKey("Id");

            b.HasIndex("TenantId");

            b.HasIndex("Name", "TenantId")
                      .IsUnique();

            b.ToTable("Tags");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Tenant", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Name")
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.HasKey("Id");

            b.ToTable("Tenants");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.TenantInvite", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("ActivationCode")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("InviteeEmail")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ActivationCode");

            b.HasIndex("TenantId");

            b.ToTable("TenantInvites");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.TenantSetting", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.Property<string>("Value")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.HasKey("Id");

            b.HasIndex("TenantId");

            b.HasIndex("Name", "TenantId")
                      .IsUnique();

            b.ToTable("TenantSettings");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserGroup", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Description")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid>("TenantId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("TenantId", "Name")
                      .IsUnique();

            b.ToTable("UserGroups");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserGroupMember", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<Guid>("UserGroupId")
                      .HasColumnType("uuid");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.HasIndex("UserGroupId", "UserId")
                      .IsUnique();

            b.ToTable("UserGroupMembers");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserPreference", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.Property<string>("Value")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.HasIndex("Name", "UserId")
                      .IsUnique();

            b.ToTable("UserPreferences");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserStorageItem", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTimeOffset>("CreatedAt")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("timestamp with time zone")
                      .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Key")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("character varying(256)");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.Property<string>("Value")
                      .IsRequired()
                      .HasMaxLength(2048)
                      .HasColumnType("character varying(2048)");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.HasIndex("Key", "UserId")
                      .IsUnique();

            b.ToTable("UserStorageItems");
          });

      modelBuilder.Entity("DeviceTag", b =>
          {
            b.Property<Guid>("DevicesId")
                      .HasColumnType("uuid");

            b.Property<Guid>("TagsId")
                      .HasColumnType("uuid");

            b.HasKey("DevicesId", "TagsId");

            b.HasIndex("TagsId");

            b.ToTable("DeviceTag");
          });

      modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("FriendlyName")
                      .HasColumnType("text");

            b.Property<string>("Xml")
                      .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("DataProtectionKeys");
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("ClaimType")
                      .HasColumnType("text");

            b.Property<string>("ClaimValue")
                      .HasColumnType("text");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserClaims", (string)null);
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
          {
            b.Property<string>("LoginProvider")
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)");

            b.Property<string>("ProviderKey")
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)");

            b.Property<string>("ProviderDisplayName")
                      .HasColumnType("text");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.HasKey("LoginProvider", "ProviderKey");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserLogins", (string)null);
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
          {
            b.Property<byte[]>("CredentialId")
                      .HasMaxLength(1024)
                      .HasColumnType("bytea");

            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.HasKey("CredentialId");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserPasskeys", (string)null);
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
          {
            b.Property<Guid>("UserId")
                      .HasColumnType("uuid");

            b.Property<string>("LoginProvider")
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)");

            b.Property<string>("Name")
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)");

            b.Property<string>("Value")
                      .HasColumnType("text");

            b.HasKey("UserId", "LoginProvider", "Name");

            b.ToTable("AspNetUserTokens", (string)null);
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AgentInstallerKey", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany()
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AgentInstallerKeyUsage", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AgentInstallerKey", "AgentInstallerKey")
                      .WithMany("Usages")
                      .HasForeignKey("AgentInstallerKeyId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany()
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("AgentInstallerKey");

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AppUser", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("Users")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Customer", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("Customers")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Device", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Customer", "Customer")
                      .WithMany()
                      .HasForeignKey("CustomerId")
                      .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("Devices")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.OwnsMany("ControlR.Libraries.Api.Contracts.Dtos.Devices.Drive", "Drives", b1 =>
                      {
                    b1.Property<Guid>("DeviceId");

                    b1.Property<int>("__synthesizedOrdinal")
                              .ValueGeneratedOnAdd();

                    b1.Property<string>("DriveFormat")
                              .IsRequired();

                    b1.Property<int>("DriveType");

                    b1.Property<double>("FreeSpace");

                    b1.Property<string>("Name")
                              .IsRequired();

                    b1.Property<string>("RootDirectory")
                              .IsRequired();

                    b1.Property<double>("TotalSize");

                    b1.Property<string>("VolumeLabel")
                              .IsRequired();

                    b1.HasKey("DeviceId", "__synthesizedOrdinal");

                    b1.ToTable("Devices");

                    b1
                              .ToJson("Drives")
                              .HasColumnType("jsonb");

                    b1.WithOwner()
                              .HasForeignKey("DeviceId");
                  });

            b.Navigation("Customer");

            b.Navigation("Drives");

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.DeviceGroup", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("DeviceGroups")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.DeviceGroupMember", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.DeviceGroup", "DeviceGroup")
                      .WithMany("Members")
                      .HasForeignKey("DeviceGroupId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("ControlR.Web.Server.Data.Entities.Device", "Device")
                      .WithMany("DeviceGroupMembers")
                      .HasForeignKey("DeviceId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Device");

            b.Navigation("DeviceGroup");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.LogonToken", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Device", "Device")
                      .WithMany("LogonTokens")
                      .HasForeignKey("DeviceId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("LogonTokens")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", "User")
                      .WithMany("LogonTokens")
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Device");

            b.Navigation("Tenant");

            b.Navigation("User");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.PersonalAccessToken", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", "User")
                      .WithMany("PersonalAccessTokens")
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("User");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.ServiceAccount", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany()
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade);

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.ServiceAccountCredential", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.ServiceAccount", "ServiceAccount")
                      .WithMany("Credentials")
                      .HasForeignKey("ServiceAccountId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("ServiceAccount");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Tag", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("Tags")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.TenantInvite", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("TenantInvites")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.TenantSetting", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("TenantSettings")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserGroup", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Tenant", "Tenant")
                      .WithMany("UserGroups")
                      .HasForeignKey("TenantId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Tenant");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserGroupMember", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.UserGroup", "UserGroup")
                      .WithMany("Members")
                      .HasForeignKey("UserGroupId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", "User")
                      .WithMany("UserGroupMembers")
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("User");

            b.Navigation("UserGroup");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserPreference", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", "User")
                      .WithMany("UserPreferences")
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("User");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserStorageItem", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", "User")
                      .WithMany("UserStorageItems")
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("User");
          });

      modelBuilder.Entity("DeviceTag", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.Device", null)
                      .WithMany()
                      .HasForeignKey("DevicesId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("ControlR.Web.Server.Data.Entities.Tag", null)
                      .WithMany()
                      .HasForeignKey("TagsId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", null)
                      .WithMany()
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", null)
                      .WithMany()
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", null)
                      .WithMany()
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                      {
                    b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                    b1.Property<byte[]>("AttestationObject")
                              .IsRequired();

                    b1.Property<byte[]>("ClientDataJson")
                              .IsRequired();

                    b1.Property<DateTimeOffset>("CreatedAt");

                    b1.Property<bool>("IsBackedUp");

                    b1.Property<bool>("IsBackupEligible");

                    b1.Property<bool>("IsUserVerified");

                    b1.Property<string>("Name");

                    b1.Property<byte[]>("PublicKey")
                              .IsRequired();

                    b1.Property<long>("SignCount");

                    b1.PrimitiveCollection<string>("Transports");

                    b1.HasKey("IdentityUserPasskeyCredentialId");

                    b1.ToTable("AspNetUserPasskeys");

                    b1
                              .ToJson("Data")
                              .HasColumnType("jsonb");

                    b1.WithOwner()
                              .HasForeignKey("IdentityUserPasskeyCredentialId");
                  });

            b.Navigation("Data")
                      .IsRequired();
          });

      modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
          {
            b.HasOne("ControlR.Web.Server.Data.Entities.AppUser", null)
                      .WithMany()
                      .HasForeignKey("UserId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AgentInstallerKey", b =>
          {
            b.Navigation("Usages");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.AppUser", b =>
          {
            b.Navigation("LogonTokens");

            b.Navigation("PersonalAccessTokens");

            b.Navigation("UserGroupMembers");

            b.Navigation("UserPreferences");

            b.Navigation("UserStorageItems");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Device", b =>
          {
            b.Navigation("DeviceGroupMembers");

            b.Navigation("LogonTokens");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.DeviceGroup", b =>
          {
            b.Navigation("Members");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.ServiceAccount", b =>
          {
            b.Navigation("Credentials");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.Tenant", b =>
          {
            b.Navigation("Customers");

            b.Navigation("DeviceGroups");

            b.Navigation("Devices");

            b.Navigation("LogonTokens");

            b.Navigation("Tags");

            b.Navigation("TenantInvites");

            b.Navigation("TenantSettings");

            b.Navigation("UserGroups");

            b.Navigation("Users");
          });

      modelBuilder.Entity("ControlR.Web.Server.Data.Entities.UserGroup", b =>
          {
            b.Navigation("Members");
          });
#pragma warning restore 612, 618
    }
  }
}
