//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlR.Viewer.Avalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlR.Viewer.Avalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Pan.
        /// </summary>
        public static string AutoPan {
            get {
                return ResourceManager.GetString("AutoPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User Input.
        /// </summary>
        public static string BlockUserInput {
            get {
                return ResourceManager.GetString("BlockUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Connection.
        /// </summary>
        public static string CloseConnection {
            get {
                return ResourceManager.GetString("CloseConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Quality Lower Threshold.
        /// </summary>
        public static string AutoQualityLowerThreshold {
            get {
                return ResourceManager.GetString("AutoQualityLowerThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Quality Maximum.
        /// </summary>
        public static string AutoQualityMaximum {
            get {
                return ResourceManager.GetString("AutoQualityMaximum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Quality Minimum.
        /// </summary>
        public static string AutoQualityMinimum {
            get {
                return ResourceManager.GetString("AutoQualityMinimum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Quality Upper Threshold.
        /// </summary>
        public static string AutoQualityUpperThreshold {
            get {
                return ResourceManager.GetString("AutoQualityUpperThreshold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capture Cursor.
        /// </summary>
        public static string CaptureCursor {
            get {
                return ResourceManager.GetString("CaptureCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        public static string ConnectionStatus_Reconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ConnectionStatus_Unknown {
            get {
                return ResourceManager.GetString("ConnectionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseUrl is required. Set the BaseUrl property in the Options..
        /// </summary>
        public static string ControlrViewer_BaseUrlRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_BaseUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get Clipboard from TopLevel. Ensure the application supports clipboard operations..
        /// </summary>
        public static string ControlrViewer_ClipboardMissing {
            get {
                return ResourceManager.GetString("ControlrViewer_ClipboardMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceId is required. Set the DeviceId property in the Options..
        /// </summary>
        public static string ControlrViewer_DeviceIdRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_DeviceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during initialization: {0}.
        /// </summary>
        public static string ControlrViewer_InitializationError {
            get {
                return ResourceManager.GetString("ControlrViewer_InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options have not been set..
        /// </summary>
        public static string ControlrViewer_OptionsNotSet {
            get {
                return ResourceManager.GetString("ControlrViewer_OptionsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlrViewer requires an Options instance. Set the Options property in XAML or code..
        /// </summary>
        public static string ControlrViewer_OptionsRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_OptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalAccessToken is required. Set the PersonalAccessToken property in the Options..
        /// </summary>
        public static string ControlrViewer_PatRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_PatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service provider has not been initialized..
        /// </summary>
        public static string ControlrViewer_ServiceProviderNotInitialized {
            get {
                return ResourceManager.GetString("ControlrViewer_ServiceProviderNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get TopLevel from ControlrViewer. Ensure it is part of the visual tree..
        /// </summary>
        public static string ControlrViewer_TopLevelMissing {
            get {
                return ResourceManager.GetString("ControlrViewer_TopLevelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Del.
        /// </summary>
        public static string CtrlAltDel {
            get {
                return ResourceManager.GetString("CtrlAltDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device info..
        /// </summary>
        public static string DeviceInfo_RetrievalFailed {
            get {
                return ResourceManager.GetString("DeviceInfo_RetrievalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device info.
        ///
        ///Details: {0}.
        /// </summary>
        public static string DeviceInfo_RetrievalFailedDetails {
            get {
                return ResourceManager.GetString("DeviceInfo_RetrievalFailedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Quality.
        /// </summary>
        public static string EnableAutoQuality {
            get {
                return ResourceManager.GetString("EnableAutoQuality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Max Mbps.
        /// </summary>
        public static string EnableMaxBandwidth {
            get {
                return ResourceManager.GetString("EnableMaxBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays.
        /// </summary>
        public static string Displays {
            get {
                return ResourceManager.GetString("Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Input Mode.
        /// </summary>
        public static string KeyboardInputMode {
            get {
                return ResourceManager.GetString("KeyboardInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string KeyboardMode_Auto {
            get {
                return ResourceManager.GetString("KeyboardMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        public static string KeyboardMode_Physical {
            get {
                return ResourceManager.GetString("KeyboardMode_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        public static string KeyboardMode_Virtual {
            get {
                return ResourceManager.GetString("KeyboardMode_Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency:.
        /// </summary>
        public static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps In:.
        /// </summary>
        public static string MbpsIn {
            get {
                return ResourceManager.GetString("MbpsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps Out:.
        /// </summary>
        public static string MbpsOut {
            get {
                return ResourceManager.GetString("MbpsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quality:.
        /// </summary>
        public static string Metrics_CurrentQualityLabel {
            get {
                return ResourceManager.GetString("Metrics_CurrentQualityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string Metrics_FpsLabel {
            get {
                return ResourceManager.GetString("Metrics_FpsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latency:.
        /// </summary>
        public static string Metrics_LatencyLabel {
            get {
                return ResourceManager.GetString("Metrics_LatencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps In:.
        /// </summary>
        public static string Metrics_MbpsInLabel {
            get {
                return ResourceManager.GetString("Metrics_MbpsInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps Out:.
        /// </summary>
        public static string Metrics_MbpsOutLabel {
            get {
                return ResourceManager.GetString("Metrics_MbpsOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string Metrics_ModeLabel {
            get {
                return ResourceManager.GetString("Metrics_ModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manual Quality.
        /// </summary>
        public static string ManualQuality {
            get {
                return ResourceManager.GetString("ManualQuality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max Mbps.
        /// </summary>
        public static string MaxBandwidthMbps {
            get {
                return ResourceManager.GetString("MaxBandwidthMbps", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Screen.
        /// </summary>
        public static string PrivacyScreen {
            get {
                return ResourceManager.GetString("PrivacyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string ProcessID {
            get {
                return ResourceManager.GetString("ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Clipboard.
        /// </summary>
        public static string ReceiveClipboard {
            get {
                return ResourceManager.GetString("ReceiveClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Sessions.
        /// </summary>
        public static string RefreshSessions {
            get {
                return ResourceManager.GetString("RefreshSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string FileSystem_AddressLabel {
            get {
                return ResourceManager.GetString("FileSystem_AddressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FileSystem_CancelButtonText {
            get {
                return ResourceManager.GetString("FileSystem_CancelButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create the folder.
        /// </summary>
        public static string FileSystem_CreateFolderFailureDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_CreateFolderFailureDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_CreateFolderFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_CreateFolderFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_CreateFolderSuccessMessage {
            get {
                return ResourceManager.GetString("FileSystem_CreateFolderSuccessMessage", resourceCulture);
            }
        }

        public static string FileSystem_DeleteButtonText {
            get {
                return ResourceManager.GetString("FileSystem_DeleteButtonText", resourceCulture);
            }
        }

        public static string FileSystem_DeleteDialogTitle {
            get {
                return ResourceManager.GetString("FileSystem_DeleteDialogTitle", resourceCulture);
            }
        }

        public static string FileSystem_DeleteFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_DeleteFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_DeleteMultipleMessage {
            get {
                return ResourceManager.GetString("FileSystem_DeleteMultipleMessage", resourceCulture);
            }
        }

        public static string FileSystem_DeleteSingleMessage {
            get {
                return ResourceManager.GetString("FileSystem_DeleteSingleMessage", resourceCulture);
            }
        }

        public static string FileSystem_DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("FileSystem_DeleteSuccessMessage", resourceCulture);
            }
        }

        public static string FileSystem_DirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("FileSystem_DirectoryNotFoundMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadButtonText {
            get {
                return ResourceManager.GetString("FileSystem_DownloadButtonText", resourceCulture);
            }
        }

        public static string FileSystem_DownloadAlreadyInProgressMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadAlreadyInProgressMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadFailureDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadFailureDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadPreparingMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadPreparingMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadProgressKnownSizeMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadProgressKnownSizeMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadProgressTitle {
            get {
                return ResourceManager.GetString("FileSystem_DownloadProgressTitle", resourceCulture);
            }
        }

        public static string FileSystem_DownloadProgressUnknownSizeMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadProgressUnknownSizeMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadSavedMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadSavedMessage", resourceCulture);
            }
        }

        public static string FileSystem_DownloadSizeExceededMessage {
            get {
                return ResourceManager.GetString("FileSystem_DownloadSizeExceededMessage", resourceCulture);
            }
        }

        public static string FileSystem_EntryTypeFile {
            get {
                return ResourceManager.GetString("FileSystem_EntryTypeFile", resourceCulture);
            }
        }

        public static string FileSystem_EntryTypeFolder {
            get {
                return ResourceManager.GetString("FileSystem_EntryTypeFolder", resourceCulture);
            }
        }

        public static string FileSystem_FoldersHeading {
            get {
                return ResourceManager.GetString("FileSystem_FoldersHeading", resourceCulture);
            }
        }

        public static string FileSystem_GoButtonText {
            get {
                return ResourceManager.GetString("FileSystem_GoButtonText", resourceCulture);
            }
        }

        public static string FileSystem_LoadContentsFailureDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_LoadContentsFailureDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_LoadContentsFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_LoadContentsFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_LoadDrivesFailureDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_LoadDrivesFailureDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_LoadDrivesFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_LoadDrivesFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_LoadingDirectoryContents {
            get {
                return ResourceManager.GetString("FileSystem_LoadingDirectoryContents", resourceCulture);
            }
        }

        public static string FileSystem_LoadingDrives {
            get {
                return ResourceManager.GetString("FileSystem_LoadingDrives", resourceCulture);
            }
        }

        public static string FileSystem_MaxTransferSizeFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_MaxTransferSizeFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_ModifiedColumnHeader {
            get {
                return ResourceManager.GetString("FileSystem_ModifiedColumnHeader", resourceCulture);
            }
        }

        public static string FileSystem_NameColumnHeader {
            get {
                return ResourceManager.GetString("FileSystem_NameColumnHeader", resourceCulture);
            }
        }

        public static string FileSystem_NavigateErrorMessage {
            get {
                return ResourceManager.GetString("FileSystem_NavigateErrorMessage", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderButtonText {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderButtonText", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderDialogTitle {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderDialogTitle", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderHint {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderHint", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderLabel {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderLabel", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderSubtitle {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderSubtitle", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderValidationInvalidCharacter {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderValidationInvalidCharacter", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderValidationRequired {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderValidationRequired", resourceCulture);
            }
        }

        public static string FileSystem_NewFolderValidationTrailingCharacter {
            get {
                return ResourceManager.GetString("FileSystem_NewFolderValidationTrailingCharacter", resourceCulture);
            }
        }

        public static string FileSystem_NoDrivesMessage {
            get {
                return ResourceManager.GetString("FileSystem_NoDrivesMessage", resourceCulture);
            }
        }

        public static string FileSystem_OverwriteButtonText {
            get {
                return ResourceManager.GetString("FileSystem_OverwriteButtonText", resourceCulture);
            }
        }

        public static string FileSystem_OverwriteDialogMessage {
            get {
                return ResourceManager.GetString("FileSystem_OverwriteDialogMessage", resourceCulture);
            }
        }

        public static string FileSystem_OverwriteDialogTitle {
            get {
                return ResourceManager.GetString("FileSystem_OverwriteDialogTitle", resourceCulture);
            }
        }

        public static string FileSystem_PathNotFoundMessage {
            get {
                return ResourceManager.GetString("FileSystem_PathNotFoundMessage", resourceCulture);
            }
        }

        public static string FileSystem_PathValidationErrorDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_PathValidationErrorDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_PathValidationErrorMessage {
            get {
                return ResourceManager.GetString("FileSystem_PathValidationErrorMessage", resourceCulture);
            }
        }

        public static string FileSystem_SaveDownloadDialogTitle {
            get {
                return ResourceManager.GetString("FileSystem_SaveDownloadDialogTitle", resourceCulture);
            }
        }

        public static string FileSystem_SearchPlaceholder {
            get {
                return ResourceManager.GetString("FileSystem_SearchPlaceholder", resourceCulture);
            }
        }

        public static string FileSystem_SelectDirectoryFirst {
            get {
                return ResourceManager.GetString("FileSystem_SelectDirectoryFirst", resourceCulture);
            }
        }

        public static string FileSystem_SelectDirectoryPrompt {
            get {
                return ResourceManager.GetString("FileSystem_SelectDirectoryPrompt", resourceCulture);
            }
        }

        public static string FileSystem_SelectItemsToDelete {
            get {
                return ResourceManager.GetString("FileSystem_SelectItemsToDelete", resourceCulture);
            }
        }

        public static string FileSystem_SelectItemsToDownload {
            get {
                return ResourceManager.GetString("FileSystem_SelectItemsToDownload", resourceCulture);
            }
        }

        public static string FileSystem_SizeColumnHeader {
            get {
                return ResourceManager.GetString("FileSystem_SizeColumnHeader", resourceCulture);
            }
        }

        public static string FileSystem_SubmitButtonText {
            get {
                return ResourceManager.GetString("FileSystem_SubmitButtonText", resourceCulture);
            }
        }

        public static string FileSystem_TabTitle {
            get {
                return ResourceManager.GetString("FileSystem_TabTitle", resourceCulture);
            }
        }

        public static string FileSystem_TypeColumnHeader {
            get {
                return ResourceManager.GetString("FileSystem_TypeColumnHeader", resourceCulture);
            }
        }

        public static string FileSystem_UploadButtonText {
            get {
                return ResourceManager.GetString("FileSystem_UploadButtonText", resourceCulture);
            }
        }

        public static string FileSystem_UploadAlreadyInProgressMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadAlreadyInProgressMessage", resourceCulture);
            }
        }

        public static string FileSystem_UploadDialogTitle {
            get {
                return ResourceManager.GetString("FileSystem_UploadDialogTitle", resourceCulture);
            }
        }

        public static string FileSystem_UploadErrorMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadErrorMessage", resourceCulture);
            }
        }

        public static string FileSystem_UploadFailureDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadFailureDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_UploadProgressStatusMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadProgressStatusMessage", resourceCulture);
            }
        }

        public static string FileSystem_UploadProgressStatusWithSpeedMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadProgressStatusWithSpeedMessage", resourceCulture);
            }
        }

        public static string FileSystem_UploadProgressTitle {
            get {
                return ResourceManager.GetString("FileSystem_UploadProgressTitle", resourceCulture);
            }
        }

        public static string FileSystem_UploadSizeExceededMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadSizeExceededMessage", resourceCulture);
            }
        }

        public static string FileSystem_UploadSuccessMessage {
            get {
                return ResourceManager.GetString("FileSystem_UploadSuccessMessage", resourceCulture);
            }
        }

        public static string FileSystem_UpButtonText {
            get {
                return ResourceManager.GetString("FileSystem_UpButtonText", resourceCulture);
            }
        }

        public static string FileSystem_UpOneLevelFailureDetailsMessage {
            get {
                return ResourceManager.GetString("FileSystem_UpOneLevelFailureDetailsMessage", resourceCulture);
            }
        }

        public static string FileSystem_UpOneLevelFailureMessage {
            get {
                return ResourceManager.GetString("FileSystem_UpOneLevelFailureMessage", resourceCulture);
            }
        }

        public static string FileSystem_UpOneLevelUnavailable {
            get {
                return ResourceManager.GetString("FileSystem_UpOneLevelUnavailable", resourceCulture);
            }
        }

        public static string FileSystem_ZipArchiveFileType {
            get {
                return ResourceManager.GetString("FileSystem_ZipArchiveFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input blocking disabled.
        /// </summary>
        public static string RemoteControl_BlockInputDisabled {
            get {
                return ResourceManager.GetString("RemoteControl_BlockInputDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input blocking enabled.
        /// </summary>
        public static string RemoteControl_BlockInputEnabled {
            get {
                return ResourceManager.GetString("RemoteControl_BlockInputEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        public static string RemoteControl_ClipboardEmpty {
            get {
                return ResourceManager.GetString("RemoteControl_ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard text received from remote device.
        /// </summary>
        public static string RemoteControl_ClipboardTextReceived {
            get {
                return ResourceManager.GetString("RemoteControl_ClipboardTextReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Del sent successfully.
        /// </summary>
        public static string RemoteControl_CtrlAltDelSent {
            get {
                return ResourceManager.GetString("RemoteControl_CtrlAltDelSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Preview.
        /// </summary>
        public static string RemoteControl_DesktopPreview {
            get {
                return ResourceManager.GetString("RemoteControl_DesktopPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Session on {0}.
        /// </summary>
        public static string RemoteControl_DesktopSessionOnDevice {
            get {
                return ResourceManager.GetString("RemoteControl_DesktopSessionOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device information is not available..
        /// </summary>
        public static string RemoteControl_DeviceInfoUnavailable {
            get {
                return ResourceManager.GetString("RemoteControl_DeviceInfoUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while disconnecting from the remote control session..
        /// </summary>
        public static string RemoteControl_ErrorDisconnecting {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving clipboard.
        /// </summary>
        public static string RemoteControl_ErrorReceivingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorReceivingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while requesting the remote control session..
        /// </summary>
        public static string RemoteControl_ErrorRequestingSession {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorRequestingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while requesting remote control permissions.
        /// </summary>
        public static string RemoteControl_ErrorRequestingPermissions {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorRequestingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting remote control permissions.
        /// </summary>
        public static string RemoteControl_RequestingPermissions {
            get {
                return ResourceManager.GetString("RemoteControl_RequestingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending clipboard.
        /// </summary>
        public static string RemoteControl_ErrorSendingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorSendingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending Ctrl+Alt+Del.
        /// </summary>
        public static string RemoteControl_ErrorSendingCtrlAltDel {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorSendingCtrlAltDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling block input.
        /// </summary>
        public static string RemoteControl_ErrorTogglingBlockInput {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorTogglingBlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while typing clipboard.
        /// </summary>
        public static string RemoteControl_ErrorTypingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorTypingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable input blocking.
        /// </summary>
        public static string RemoteControl_FailedToDisableBlockInput {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToDisableBlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable privacy screen.
        /// </summary>
        public static string RemoteControl_FailedToDisablePrivacyScreen {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToDisablePrivacyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable input blocking.
        /// </summary>
        public static string RemoteControl_FailedToEnableBlockInput {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToEnableBlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable privacy screen.
        /// </summary>
        public static string RemoteControl_FailedToEnablePrivacyScreen {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToEnablePrivacyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get active sessions..
        /// </summary>
        public static string RemoteControl_FailedToGetSessions {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToGetSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reconnect..
        /// </summary>
        public static string RemoteControl_FailedToReconnect {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve desktop sessions on remote device..
        /// </summary>
        public static string RemoteControl_FailedToRetrieveSessions {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToRetrieveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send Ctrl+Alt+Del: {0}.
        /// </summary>
        public static string RemoteControl_FailedToSendCtrlAltDel {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToSendCtrlAltDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is disabled due to view-only mode..
        /// </summary>
        public static string RemoteControl_InputSuppressedViewOnlyMode {
            get {
                return ResourceManager.GetString("RemoteControl_InputSuppressedViewOnlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission request failed: {0}.
        /// </summary>
        public static string RemoteControl_PermissionRequestFailed {
            get {
                return ResourceManager.GetString("RemoteControl_PermissionRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission request granted.  Refreshing sessions.
        /// </summary>
        public static string RemoteControl_PermissionGranted {
            get {
                return ResourceManager.GetString("RemoteControl_PermissionGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions not granted.
        /// </summary>
        public static string RemoteControl_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("RemoteControl_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Now.
        /// </summary>
        public static string RemoteControl_RequestPermissionsNow {
            get {
                return ResourceManager.GetString("RemoteControl_RequestPermissionsNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a command.
        /// </summary>
        public static string Terminal_CommandWatermark {
            get {
                return ResourceManager.GetString("Terminal_CommandWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get cursor index for completions.
        /// </summary>
        public static string Terminal_FailedToGetCursorIndexForCompletions {
            get {
                return ResourceManager.GetString("Terminal_FailedToGetCursorIndexForCompletions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to start terminal.
        /// </summary>
        public static string Terminal_FailedToStart {
            get {
                return ResourceManager.GetString("Terminal_FailedToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting completions.
        /// </summary>
        public static string Terminal_GetCompletionsError {
            get {
                return ResourceManager.GetString("Terminal_GetCompletionsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal initialization error.
        /// </summary>
        public static string Terminal_InitializationError {
            get {
                return ResourceManager.GetString("Terminal_InitializationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        public static string Terminal_KeyboardShortcutsTitle {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcutsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arrow Down.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ArrowDownDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ArrowDownDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arrow Down.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ArrowDownLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ArrowDownLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arrow Up.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ArrowUpDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ArrowUpDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arrow Up.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ArrowUpLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ArrowUpLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show all completions.
        /// </summary>
        public static string Terminal_KeyboardShortcut_CtrlPeriodDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_CtrlPeriodDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl + ..
        /// </summary>
        public static string Terminal_KeyboardShortcut_CtrlPeriodLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_CtrlPeriodLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show all completions.
        /// </summary>
        public static string Terminal_KeyboardShortcut_CtrlSpaceDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_CtrlSpaceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Space.
        /// </summary>
        public static string Terminal_KeyboardShortcut_CtrlSpaceLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_CtrlSpaceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close completions.
        /// </summary>
        public static string Terminal_KeyboardShortcut_EscapeDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_EscapeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string Terminal_KeyboardShortcut_EscapeLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_EscapeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute command.
        /// </summary>
        public static string Terminal_KeyboardShortcut_EnterDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_EnterDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Terminal_KeyboardShortcut_EnterLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_EnterLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift + Enter.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ShiftEnterDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ShiftEnterDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift + Enter.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ShiftEnterLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ShiftEnterLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous completion.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ShiftTabDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ShiftTabDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift + Tab.
        /// </summary>
        public static string Terminal_KeyboardShortcut_ShiftTabLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_ShiftTabLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next completion.
        /// </summary>
        public static string Terminal_KeyboardShortcut_TabDescription {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_TabDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string Terminal_KeyboardShortcut_TabLabel {
            get {
                return ResourceManager.GetString("Terminal_KeyboardShortcut_TabLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading terminal.
        /// </summary>
        public static string Terminal_Loading {
            get {
                return ResourceManager.GetString("Terminal_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiline Input.
        /// </summary>
        public static string Terminal_MultilineInput {
            get {
                return ResourceManager.GetString("Terminal_MultilineInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending terminal input.
        /// </summary>
        public static string Terminal_SendInputError {
            get {
                return ResourceManager.GetString("Terminal_SendInputError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Too many items to retrieve ({0}).
        /// </summary>
        public static string Terminal_TooManyCompletionItems {
            get {
                return ResourceManager.GetString("Terminal_TooManyCompletionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview....
        /// </summary>
        public static string RemoteControl_LoadingPreview {
            get {
                return ResourceManager.GetString("RemoteControl_LoadingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active remote session.
        /// </summary>
        public static string RemoteControl_NoActiveSession {
            get {
                return ResourceManager.GetString("RemoteControl_NoActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No desktop sessions available..
        /// </summary>
        public static string RemoteControl_NoDesktopSessions {
            get {
                return ResourceManager.GetString("RemoteControl_NoDesktopSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No displays received.
        /// </summary>
        public static string RemoteControl_NoDisplaysReceived {
            get {
                return ResourceManager.GetString("RemoteControl_NoDisplaysReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview image received..
        /// </summary>
        public static string RemoteControl_NoPreviewImage {
            get {
                return ResourceManager.GetString("RemoteControl_NoPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the preview..
        /// </summary>
        public static string RemoteControl_PreviewLoadFailed {
            get {
                return ResourceManager.GetString("RemoteControl_PreviewLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview refreshed.
        /// </summary>
        public static string RemoteControl_PreviewRefreshed {
            get {
                return ResourceManager.GetString("RemoteControl_PreviewRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy screen disabled.
        /// </summary>
        public static string RemoteControl_PrivacyScreenDisabled {
            get {
                return ResourceManager.GetString("RemoteControl_PrivacyScreenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy screen enabled.
        /// </summary>
        public static string RemoteControl_PrivacyScreenEnabled {
            get {
                return ResourceManager.GetString("RemoteControl_PrivacyScreenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing sessions.
        /// </summary>
        public static string RemoteControl_RefreshingSessions {
            get {
                return ResourceManager.GetString("RemoteControl_RefreshingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote user requested disconnection.
        /// </summary>
        public static string RemoteControl_RemoteUserRequestedDisconnection {
            get {
                return ResourceManager.GetString("RemoteControl_RemoteUserRequestedDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending clipboard.
        /// </summary>
        public static string RemoteControl_SendingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_SendingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending clipboard to type.
        /// </summary>
        public static string RemoteControl_SendingClipboardToType {
            get {
                return ResourceManager.GetString("RemoteControl_SendingClipboardToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions refreshed.
        /// </summary>
        public static string RemoteControl_SessionsRefreshed {
            get {
                return ResourceManager.GetString("RemoteControl_SessionsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting remote control session.
        /// </summary>
        public static string RemoteControl_StartingSession {
            get {
                return ResourceManager.GetString("RemoteControl_StartingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach remote control input handlers..
        /// </summary>
        public static string RemoteControl_UnableToAttachHandlers {
            get {
                return ResourceManager.GetString("RemoteControl_UnableToAttachHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected signaling state..
        /// </summary>
        public static string RemoteControl_UnexpectedSignalingState {
            get {
                return ResourceManager.GetString("RemoteControl_UnexpectedSignalingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported DTO type: {0}.
        /// </summary>
        public static string RemoteControl_UnsupportedDtoType {
            get {
                return ResourceManager.GetString("RemoteControl_UnsupportedDtoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Windows session ending.
        /// </summary>
        public static string RemoteControl_WindowsSessionEnding {
            get {
                return ResourceManager.GetString("RemoteControl_WindowsSessionEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Windows session switched.
        /// </summary>
        public static string RemoteControl_WindowsSessionSwitched {
            get {
                return ResourceManager.GetString("RemoteControl_WindowsSessionSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Level.
        /// </summary>
        public static string ScaleLevel {
            get {
                return ResourceManager.GetString("ScaleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Desktop Session.
        /// </summary>
        public static string SelectDesktopSessionTitle {
            get {
                return ResourceManager.GetString("SelectDesktopSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Clipboard.
        /// </summary>
        public static string SendClipboard {
            get {
                return ResourceManager.GetString("SendClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start View Only.
        /// </summary>
        public static string StartViewOnly {
            get {
                return ResourceManager.GetString("StartViewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleOffText {
            get {
                return ResourceManager.GetString("ToggleOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleOnText {
            get {
                return ResourceManager.GetString("ToggleOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Clipboard.
        /// </summary>
        public static string TypeClipboard {
            get {
                return ResourceManager.GetString("TypeClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access. Check the provided Personal Access Token..
        /// </summary>
        public static string UnauthorizedAccessPat {
            get {
                return ResourceManager.GetString("UnauthorizedAccessPat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Viewer Hub..
        /// </summary>
        public static string ViewerHub_ConnectionFailed {
            get {
                return ResourceManager.GetString("ViewerHub_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer reconnect failed..
        /// </summary>
        public static string ViewerHub_ReconnectFailed {
            get {
                return ResourceManager.GetString("ViewerHub_ReconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent went offline..
        /// </summary>
        public static string ViewerShell_AgentWentOffline {
            get {
                return ResourceManager.GetString("ViewerShell_AgentWentOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is offline..
        /// </summary>
        public static string ViewerShell_DeviceOffline {
            get {
                return ResourceManager.GetString("ViewerShell_DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create view: {0}.
        /// </summary>
        public static string ViewLocator_CouldNotCreateView {
            get {
                return ResourceManager.GetString("ViewLocator_CouldNotCreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading view. Param: {0}. Exception: {1}.
        /// </summary>
        public static string ViewLocator_ErrorLoadingView {
            get {
                return ResourceManager.GetString("ViewLocator_ErrorLoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid view model type.
        /// </summary>
        public static string ViewLocator_InvalidViewModelType {
            get {
                return ResourceManager.GetString("ViewLocator_InvalidViewModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The viewer instance ID should not be empty here. Did you forget to implement {0} on a design-time view model?.
        /// </summary>
        public static string ViewLocator_ViewerInstanceIdEmpty {
            get {
                return ResourceManager.GetString("ViewLocator_ViewerInstanceIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View not found: {0}.
        /// </summary>
        public static string ViewLocator_ViewNotFound {
            get {
                return ResourceManager.GetString("ViewLocator_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string ViewMode_Fit {
            get {
                return ResourceManager.GetString("ViewMode_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string ViewMode_Scale {
            get {
                return ResourceManager.GetString("ViewMode_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ViewMode_Stretch {
            get {
                return ResourceManager.GetString("ViewMode_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Only.
        /// </summary>
        public static string ViewOnly {
            get {
                return ResourceManager.GetString("ViewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Keyboard.
        /// </summary>
        public static string VirtualKeyboard {
            get {
                return ResourceManager.GetString("VirtualKeyboard", resourceCulture);
            }
        }
    }
}
