//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlR.Viewer.Avalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlR.Viewer.Avalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Pan.
        /// </summary>
        public static string AutoPan {
            get {
                return ResourceManager.GetString("AutoPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User Input.
        /// </summary>
        public static string BlockUserInput {
            get {
                return ResourceManager.GetString("BlockUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Connection.
        /// </summary>
        public static string CloseConnection {
            get {
                return ResourceManager.GetString("CloseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        public static string ConnectionStatus_Reconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ConnectionStatus_Unknown {
            get {
                return ResourceManager.GetString("ConnectionStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseUrl is required. Set the BaseUrl property in the Options..
        /// </summary>
        public static string ControlrViewer_BaseUrlRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_BaseUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get Clipboard from TopLevel. Ensure the application supports clipboard operations..
        /// </summary>
        public static string ControlrViewer_ClipboardMissing {
            get {
                return ResourceManager.GetString("ControlrViewer_ClipboardMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceId is required. Set the DeviceId property in the Options..
        /// </summary>
        public static string ControlrViewer_DeviceIdRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_DeviceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during initialization: {0}.
        /// </summary>
        public static string ControlrViewer_InitializationError {
            get {
                return ResourceManager.GetString("ControlrViewer_InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options have not been set..
        /// </summary>
        public static string ControlrViewer_OptionsNotSet {
            get {
                return ResourceManager.GetString("ControlrViewer_OptionsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlrViewer requires an Options instance. Set the Options property in XAML or code..
        /// </summary>
        public static string ControlrViewer_OptionsRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_OptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalAccessToken is required. Set the PersonalAccessToken property in the Options..
        /// </summary>
        public static string ControlrViewer_PatRequired {
            get {
                return ResourceManager.GetString("ControlrViewer_PatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service provider has not been initialized..
        /// </summary>
        public static string ControlrViewer_ServiceProviderNotInitialized {
            get {
                return ResourceManager.GetString("ControlrViewer_ServiceProviderNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get TopLevel from ControlrViewer. Ensure it is part of the visual tree..
        /// </summary>
        public static string ControlrViewer_TopLevelMissing {
            get {
                return ResourceManager.GetString("ControlrViewer_TopLevelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Del.
        /// </summary>
        public static string CtrlAltDel {
            get {
                return ResourceManager.GetString("CtrlAltDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device info..
        /// </summary>
        public static string DeviceInfo_RetrievalFailed {
            get {
                return ResourceManager.GetString("DeviceInfo_RetrievalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device info.
        ///
        ///Details: {0}.
        /// </summary>
        public static string DeviceInfo_RetrievalFailedDetails {
            get {
                return ResourceManager.GetString("DeviceInfo_RetrievalFailedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays.
        /// </summary>
        public static string Displays {
            get {
                return ResourceManager.GetString("Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Input Mode.
        /// </summary>
        public static string KeyboardInputMode {
            get {
                return ResourceManager.GetString("KeyboardInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string KeyboardMode_Auto {
            get {
                return ResourceManager.GetString("KeyboardMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        public static string KeyboardMode_Physical {
            get {
                return ResourceManager.GetString("KeyboardMode_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        public static string KeyboardMode_Virtual {
            get {
                return ResourceManager.GetString("KeyboardMode_Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency:.
        /// </summary>
        public static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps In:.
        /// </summary>
        public static string MbpsIn {
            get {
                return ResourceManager.GetString("MbpsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps Out:.
        /// </summary>
        public static string MbpsOut {
            get {
                return ResourceManager.GetString("MbpsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string Metrics_FpsLabel {
            get {
                return ResourceManager.GetString("Metrics_FpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency:.
        /// </summary>
        public static string Metrics_LatencyLabel {
            get {
                return ResourceManager.GetString("Metrics_LatencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps In:.
        /// </summary>
        public static string Metrics_MbpsInLabel {
            get {
                return ResourceManager.GetString("Metrics_MbpsInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps Out:.
        /// </summary>
        public static string Metrics_MbpsOutLabel {
            get {
                return ResourceManager.GetString("Metrics_MbpsOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string Metrics_ModeLabel {
            get {
                return ResourceManager.GetString("Metrics_ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Screen.
        /// </summary>
        public static string PrivacyScreen {
            get {
                return ResourceManager.GetString("PrivacyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string ProcessID {
            get {
                return ResourceManager.GetString("ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Clipboard.
        /// </summary>
        public static string ReceiveClipboard {
            get {
                return ResourceManager.GetString("ReceiveClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Sessions.
        /// </summary>
        public static string RefreshSessions {
            get {
                return ResourceManager.GetString("RefreshSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input blocking disabled.
        /// </summary>
        public static string RemoteControl_BlockInputDisabled {
            get {
                return ResourceManager.GetString("RemoteControl_BlockInputDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input blocking enabled.
        /// </summary>
        public static string RemoteControl_BlockInputEnabled {
            get {
                return ResourceManager.GetString("RemoteControl_BlockInputEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        public static string RemoteControl_ClipboardEmpty {
            get {
                return ResourceManager.GetString("RemoteControl_ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard text received from remote device.
        /// </summary>
        public static string RemoteControl_ClipboardTextReceived {
            get {
                return ResourceManager.GetString("RemoteControl_ClipboardTextReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Del sent successfully.
        /// </summary>
        public static string RemoteControl_CtrlAltDelSent {
            get {
                return ResourceManager.GetString("RemoteControl_CtrlAltDelSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Preview.
        /// </summary>
        public static string RemoteControl_DesktopPreview {
            get {
                return ResourceManager.GetString("RemoteControl_DesktopPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Session on {0}.
        /// </summary>
        public static string RemoteControl_DesktopSessionOnDevice {
            get {
                return ResourceManager.GetString("RemoteControl_DesktopSessionOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device information is not available..
        /// </summary>
        public static string RemoteControl_DeviceInfoUnavailable {
            get {
                return ResourceManager.GetString("RemoteControl_DeviceInfoUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while disconnecting from the remote control session..
        /// </summary>
        public static string RemoteControl_ErrorDisconnecting {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving clipboard.
        /// </summary>
        public static string RemoteControl_ErrorReceivingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorReceivingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while requesting the remote control session..
        /// </summary>
        public static string RemoteControl_ErrorRequestingSession {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorRequestingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending clipboard.
        /// </summary>
        public static string RemoteControl_ErrorSendingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorSendingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending Ctrl+Alt+Del.
        /// </summary>
        public static string RemoteControl_ErrorSendingCtrlAltDel {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorSendingCtrlAltDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while toggling block input.
        /// </summary>
        public static string RemoteControl_ErrorTogglingBlockInput {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorTogglingBlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while typing clipboard.
        /// </summary>
        public static string RemoteControl_ErrorTypingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_ErrorTypingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable input blocking.
        /// </summary>
        public static string RemoteControl_FailedToDisableBlockInput {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToDisableBlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable privacy screen.
        /// </summary>
        public static string RemoteControl_FailedToDisablePrivacyScreen {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToDisablePrivacyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable input blocking.
        /// </summary>
        public static string RemoteControl_FailedToEnableBlockInput {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToEnableBlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable privacy screen.
        /// </summary>
        public static string RemoteControl_FailedToEnablePrivacyScreen {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToEnablePrivacyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get active sessions..
        /// </summary>
        public static string RemoteControl_FailedToGetSessions {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToGetSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reconnect..
        /// </summary>
        public static string RemoteControl_FailedToReconnect {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve desktop sessions on remote device..
        /// </summary>
        public static string RemoteControl_FailedToRetrieveSessions {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToRetrieveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send Ctrl+Alt+Del: {0}.
        /// </summary>
        public static string RemoteControl_FailedToSendCtrlAltDel {
            get {
                return ResourceManager.GetString("RemoteControl_FailedToSendCtrlAltDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is disabled due to view-only mode..
        /// </summary>
        public static string RemoteControl_InputSuppressedViewOnlyMode {
            get {
                return ResourceManager.GetString("RemoteControl_InputSuppressedViewOnlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview....
        /// </summary>
        public static string RemoteControl_LoadingPreview {
            get {
                return ResourceManager.GetString("RemoteControl_LoadingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active remote session.
        /// </summary>
        public static string RemoteControl_NoActiveSession {
            get {
                return ResourceManager.GetString("RemoteControl_NoActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No desktop sessions available..
        /// </summary>
        public static string RemoteControl_NoDesktopSessions {
            get {
                return ResourceManager.GetString("RemoteControl_NoDesktopSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No displays received.
        /// </summary>
        public static string RemoteControl_NoDisplaysReceived {
            get {
                return ResourceManager.GetString("RemoteControl_NoDisplaysReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview image received..
        /// </summary>
        public static string RemoteControl_NoPreviewImage {
            get {
                return ResourceManager.GetString("RemoteControl_NoPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the preview..
        /// </summary>
        public static string RemoteControl_PreviewLoadFailed {
            get {
                return ResourceManager.GetString("RemoteControl_PreviewLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview refreshed.
        /// </summary>
        public static string RemoteControl_PreviewRefreshed {
            get {
                return ResourceManager.GetString("RemoteControl_PreviewRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy screen disabled.
        /// </summary>
        public static string RemoteControl_PrivacyScreenDisabled {
            get {
                return ResourceManager.GetString("RemoteControl_PrivacyScreenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy screen enabled.
        /// </summary>
        public static string RemoteControl_PrivacyScreenEnabled {
            get {
                return ResourceManager.GetString("RemoteControl_PrivacyScreenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing sessions.
        /// </summary>
        public static string RemoteControl_RefreshingSessions {
            get {
                return ResourceManager.GetString("RemoteControl_RefreshingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote user requested disconnection.
        /// </summary>
        public static string RemoteControl_RemoteUserRequestedDisconnection {
            get {
                return ResourceManager.GetString("RemoteControl_RemoteUserRequestedDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending clipboard.
        /// </summary>
        public static string RemoteControl_SendingClipboard {
            get {
                return ResourceManager.GetString("RemoteControl_SendingClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending clipboard to type.
        /// </summary>
        public static string RemoteControl_SendingClipboardToType {
            get {
                return ResourceManager.GetString("RemoteControl_SendingClipboardToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions refreshed.
        /// </summary>
        public static string RemoteControl_SessionsRefreshed {
            get {
                return ResourceManager.GetString("RemoteControl_SessionsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting remote control session.
        /// </summary>
        public static string RemoteControl_StartingSession {
            get {
                return ResourceManager.GetString("RemoteControl_StartingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach remote control input handlers..
        /// </summary>
        public static string RemoteControl_UnableToAttachHandlers {
            get {
                return ResourceManager.GetString("RemoteControl_UnableToAttachHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected signaling state..
        /// </summary>
        public static string RemoteControl_UnexpectedSignalingState {
            get {
                return ResourceManager.GetString("RemoteControl_UnexpectedSignalingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported DTO type: {0}.
        /// </summary>
        public static string RemoteControl_UnsupportedDtoType {
            get {
                return ResourceManager.GetString("RemoteControl_UnsupportedDtoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Windows session ending.
        /// </summary>
        public static string RemoteControl_WindowsSessionEnding {
            get {
                return ResourceManager.GetString("RemoteControl_WindowsSessionEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Windows session switched.
        /// </summary>
        public static string RemoteControl_WindowsSessionSwitched {
            get {
                return ResourceManager.GetString("RemoteControl_WindowsSessionSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Level.
        /// </summary>
        public static string ScaleLevel {
            get {
                return ResourceManager.GetString("ScaleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Desktop Session.
        /// </summary>
        public static string SelectDesktopSessionTitle {
            get {
                return ResourceManager.GetString("SelectDesktopSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Clipboard.
        /// </summary>
        public static string SendClipboard {
            get {
                return ResourceManager.GetString("SendClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start View Only.
        /// </summary>
        public static string StartViewOnly {
            get {
                return ResourceManager.GetString("StartViewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleOffText {
            get {
                return ResourceManager.GetString("ToggleOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleOnText {
            get {
                return ResourceManager.GetString("ToggleOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Clipboard.
        /// </summary>
        public static string TypeClipboard {
            get {
                return ResourceManager.GetString("TypeClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access. Check the provided Personal Access Token..
        /// </summary>
        public static string UnauthorizedAccessPat {
            get {
                return ResourceManager.GetString("UnauthorizedAccessPat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Viewer Hub..
        /// </summary>
        public static string ViewerHub_ConnectionFailed {
            get {
                return ResourceManager.GetString("ViewerHub_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer reconnect failed..
        /// </summary>
        public static string ViewerHub_ReconnectFailed {
            get {
                return ResourceManager.GetString("ViewerHub_ReconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent went offline..
        /// </summary>
        public static string ViewerShell_AgentWentOffline {
            get {
                return ResourceManager.GetString("ViewerShell_AgentWentOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is offline..
        /// </summary>
        public static string ViewerShell_DeviceOffline {
            get {
                return ResourceManager.GetString("ViewerShell_DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create view: {0}.
        /// </summary>
        public static string ViewLocator_CouldNotCreateView {
            get {
                return ResourceManager.GetString("ViewLocator_CouldNotCreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading view. Param: {0}. Exception: {1}.
        /// </summary>
        public static string ViewLocator_ErrorLoadingView {
            get {
                return ResourceManager.GetString("ViewLocator_ErrorLoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid view model type.
        /// </summary>
        public static string ViewLocator_InvalidViewModelType {
            get {
                return ResourceManager.GetString("ViewLocator_InvalidViewModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The viewer instance ID should not be empty here. Did you forget to implement {0} on a design-time view model?.
        /// </summary>
        public static string ViewLocator_ViewerInstanceIdEmpty {
            get {
                return ResourceManager.GetString("ViewLocator_ViewerInstanceIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View not found: {0}.
        /// </summary>
        public static string ViewLocator_ViewNotFound {
            get {
                return ResourceManager.GetString("ViewLocator_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string ViewMode_Fit {
            get {
                return ResourceManager.GetString("ViewMode_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string ViewMode_Scale {
            get {
                return ResourceManager.GetString("ViewMode_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ViewMode_Stretch {
            get {
                return ResourceManager.GetString("ViewMode_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Only.
        /// </summary>
        public static string ViewOnly {
            get {
                return ResourceManager.GetString("ViewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Keyboard.
        /// </summary>
        public static string VirtualKeyboard {
            get {
                return ResourceManager.GetString("VirtualKeyboard", resourceCulture);
            }
        }
    }
}
