version: '3.4'

services:
  controlr:
    image: ${DOCKER_REGISTRY-}controlrserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      #- ControlR_ApplicationOptions__AdminPublicKeys__0=
      #- ControlR_ApplicationOptions__EnableRestrictedUserAccess=
      #- ControlR_ApplicationOptions__AuthorizedUserPublicKeys__0=
    ports:
      - 5120:8080
      - 7031:8081
    build:
      context: ../
      dockerfile: ControlR.Server/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro