services:
  controlr:
    image: ${DOCKER_REGISTRY-}controlrwebserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ControlR_AspireDashboard__Token: ${ControlR_ASPIRE_BROWSER_TOKEN:?error}
    ports:
      - "5120:8080"
      - "7031:8081"
    build:
      context: ../
      dockerfile: ControlR.Web.Server/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  aspire:
    ports:
      - "18889:18889"