// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateDeviceRequestDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The device property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ControlR.ApiClient.Models.DeviceUpdateRequestDto? Device { get; set; }
#nullable restore
#else
        public global::ControlR.ApiClient.Models.DeviceUpdateRequestDto Device { get; set; }
#endif
        /// <summary>The installerKeyId property</summary>
        public Guid? InstallerKeyId { get; set; }
        /// <summary>The installerKeySecret property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstallerKeySecret { get; set; }
#nullable restore
#else
        public string InstallerKeySecret { get; set; }
#endif
        /// <summary>The tagIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TagIds { get; set; }
#nullable restore
#else
        public List<Guid?> TagIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.CreateDeviceRequestDto"/> and sets the default values.
        /// </summary>
        public CreateDeviceRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.CreateDeviceRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.CreateDeviceRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.CreateDeviceRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "device", n => { Device = n.GetObjectValue<global::ControlR.ApiClient.Models.DeviceUpdateRequestDto>(global::ControlR.ApiClient.Models.DeviceUpdateRequestDto.CreateFromDiscriminatorValue); } },
                { "installerKeyId", n => { InstallerKeyId = n.GetGuidValue(); } },
                { "installerKeySecret", n => { InstallerKeySecret = n.GetStringValue(); } },
                { "tagIds", n => { TagIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ControlR.ApiClient.Models.DeviceUpdateRequestDto>("device", Device);
            writer.WriteGuidValue("installerKeyId", InstallerKeyId);
            writer.WriteStringValue("installerKeySecret", InstallerKeySecret);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("tagIds", TagIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
