// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeviceSearchRequestDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The filterDefinitions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ControlR.ApiClient.Models.DeviceColumnFilter>? FilterDefinitions { get; set; }
#nullable restore
#else
        public List<global::ControlR.ApiClient.Models.DeviceColumnFilter> FilterDefinitions { get; set; }
#endif
        /// <summary>The hideOfflineDevices property</summary>
        public bool? HideOfflineDevices { get; set; }
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>The searchText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchText { get; set; }
#nullable restore
#else
        public string SearchText { get; set; }
#endif
        /// <summary>The sortDefinitions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ControlR.ApiClient.Models.DeviceColumnSort>? SortDefinitions { get; set; }
#nullable restore
#else
        public List<global::ControlR.ApiClient.Models.DeviceColumnSort> SortDefinitions { get; set; }
#endif
        /// <summary>The tagIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TagIds { get; set; }
#nullable restore
#else
        public List<Guid?> TagIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.DeviceSearchRequestDto"/> and sets the default values.
        /// </summary>
        public DeviceSearchRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.DeviceSearchRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.DeviceSearchRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.DeviceSearchRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filterDefinitions", n => { FilterDefinitions = n.GetCollectionOfObjectValues<global::ControlR.ApiClient.Models.DeviceColumnFilter>(global::ControlR.ApiClient.Models.DeviceColumnFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hideOfflineDevices", n => { HideOfflineDevices = n.GetBoolValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "searchText", n => { SearchText = n.GetStringValue(); } },
                { "sortDefinitions", n => { SortDefinitions = n.GetCollectionOfObjectValues<global::ControlR.ApiClient.Models.DeviceColumnSort>(global::ControlR.ApiClient.Models.DeviceColumnSort.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tagIds", n => { TagIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ControlR.ApiClient.Models.DeviceColumnFilter>("filterDefinitions", FilterDefinitions);
            writer.WriteBoolValue("hideOfflineDevices", HideOfflineDevices);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteStringValue("searchText", SearchText);
            writer.WriteCollectionOfObjectValues<global::ControlR.ApiClient.Models.DeviceColumnSort>("sortDefinitions", SortDefinitions);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("tagIds", TagIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
