// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Drive : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The driveFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DriveFormat { get; set; }
#nullable restore
#else
        public string DriveFormat { get; set; }
#endif
        /// <summary>The driveType property</summary>
        public global::ControlR.ApiClient.Models.DriveType? DriveType { get; set; }
        /// <summary>The freeSpace property</summary>
        public double? FreeSpace { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The rootDirectory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootDirectory { get; set; }
#nullable restore
#else
        public string RootDirectory { get; set; }
#endif
        /// <summary>The totalSize property</summary>
        public double? TotalSize { get; set; }
        /// <summary>The volumeLabel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VolumeLabel { get; set; }
#nullable restore
#else
        public string VolumeLabel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.Drive"/> and sets the default values.
        /// </summary>
        public Drive()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.Drive"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.Drive CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.Drive();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "driveFormat", n => { DriveFormat = n.GetStringValue(); } },
                { "driveType", n => { DriveType = n.GetEnumValue<global::ControlR.ApiClient.Models.DriveType>(); } },
                { "freeSpace", n => { FreeSpace = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "rootDirectory", n => { RootDirectory = n.GetStringValue(); } },
                { "totalSize", n => { TotalSize = n.GetDoubleValue(); } },
                { "volumeLabel", n => { VolumeLabel = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("driveFormat", DriveFormat);
            writer.WriteEnumValue<global::ControlR.ApiClient.Models.DriveType>("driveType", DriveType);
            writer.WriteDoubleValue("freeSpace", FreeSpace);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("rootDirectory", RootDirectory);
            writer.WriteDoubleValue("totalSize", TotalSize);
            writer.WriteStringValue("volumeLabel", VolumeLabel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
