// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServerStatsDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The onlineAgents property</summary>
        public int? OnlineAgents { get; set; }
        /// <summary>The onlineUsers property</summary>
        public int? OnlineUsers { get; set; }
        /// <summary>The totalAgents property</summary>
        public int? TotalAgents { get; set; }
        /// <summary>The totalTenants property</summary>
        public int? TotalTenants { get; set; }
        /// <summary>The totalUsers property</summary>
        public int? TotalUsers { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.ServerStatsDto"/> and sets the default values.
        /// </summary>
        public ServerStatsDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.ServerStatsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.ServerStatsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.ServerStatsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "onlineAgents", n => { OnlineAgents = n.GetIntValue(); } },
                { "onlineUsers", n => { OnlineUsers = n.GetIntValue(); } },
                { "totalAgents", n => { TotalAgents = n.GetIntValue(); } },
                { "totalTenants", n => { TotalTenants = n.GetIntValue(); } },
                { "totalUsers", n => { TotalUsers = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("onlineAgents", OnlineAgents);
            writer.WriteIntValue("onlineUsers", OnlineUsers);
            writer.WriteIntValue("totalAgents", TotalAgents);
            writer.WriteIntValue("totalTenants", TotalTenants);
            writer.WriteIntValue("totalUsers", TotalUsers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
