// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.AgentUpdate.GetHashSha256;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.AgentUpdate
{
    /// <summary>
    /// Builds and executes requests for operations under \api\agent-update
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentUpdateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getHashSha256 property</summary>
        public global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.GetHashSha256RequestBuilder GetHashSha256
        {
            get => new global::ControlR.ApiClient.Api.AgentUpdate.GetHashSha256.GetHashSha256RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.AgentUpdate.AgentUpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AgentUpdateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/agent-update", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.AgentUpdate.AgentUpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AgentUpdateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/agent-update", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
