global using Bitbound.SimpleMessenger;
global using ControlR.Libraries.DevicesCommon.Extensions;
global using ControlR.Libraries.DevicesCommon.Messages;
global using ControlR.Libraries.Shared.Collections;
global using ControlR.Viewer.Models;
global using ControlR.Viewer.Models.Messages;
global using ControlR.Libraries.DevicesCommon.Services;
global using ControlR.Libraries.Shared;
global using ControlR.Libraries.Shared.Dtos;
global using ControlR.Libraries.Shared.Enums;
global using ControlR.Libraries.Shared.Helpers;
global using ControlR.Libraries.Shared.Models;
global using ControlR.Libraries.Shared.Hubs;
global using ControlR.Libraries.Shared.Services;
global using MauiFiles = Microsoft.Maui.Storage.IFileSystem;
global using FileIO = ControlR.Libraries.DevicesCommon.Services.IFileSystem;