// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\installer-keys\increment-usage\{keyId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithKeyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithKeyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/installer-keys/increment-usage/{keyId}{?deviceId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithKeyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/installer-keys/increment-usage/{keyId}{?deviceId*}", rawUrl)
        {
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(Action<RequestConfiguration<global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder.WithKeyItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(Action<RequestConfiguration<global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder.WithKeyItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder.WithKeyItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder.WithKeyItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class WithKeyItemRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("deviceId")]
            public Guid? DeviceId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithKeyItemRequestBuilderPostRequestConfiguration : RequestConfiguration<global::ControlR.ApiClient.Api.InstallerKeys.IncrementUsage.Item.WithKeyItemRequestBuilder.WithKeyItemRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
