global using Bitbound.SimpleMessenger;
global using ControlR.Libraries.DevicesCommon.Services;
global using ControlR.Libraries.Shared.Models;
global using ControlR.Libraries.Shared.Services;
global using ControlR.Libraries.Shared;
global using ControlR.Libraries.Shared.Dtos;
global using ControlR.Libraries.Clients.Extensions;
global using ControlR.Libraries.Clients.Messages;
global using Microsoft.Extensions.Logging;