// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.VersionNamespace.Agent;
using ControlR.ApiClient.Api.VersionNamespace.Server;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.VersionNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Version
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VersionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agent property</summary>
        public global::ControlR.ApiClient.Api.VersionNamespace.Agent.AgentRequestBuilder Agent
        {
            get => new global::ControlR.ApiClient.Api.VersionNamespace.Agent.AgentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The server property</summary>
        public global::ControlR.ApiClient.Api.VersionNamespace.Server.ServerRequestBuilder Server
        {
            get => new global::ControlR.ApiClient.Api.VersionNamespace.Server.ServerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.VersionNamespace.VersionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VersionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Version", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.VersionNamespace.VersionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VersionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Version", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
