name: opencode

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  opencode:
    runs-on: ${{ fromJson('["self-hosted","Linux"]') }}

    if: |
      github.event_name == 'pull_request' ||
      ((github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment') && (
        contains(github.event.comment.body, '/oc') ||
        contains(github.event.comment.body, '/opencode')
      ))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run OpenCode
        shell: bash
        id: run_opencode
        run: opencode github run
        env:
          MODEL: ${{secrets.OPENCODE_MODEL}}