name: Tests

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (leave empty for auto)"
        required: false
        type: string
  pull_request:
    branches: 
      - main
      - dev
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "README.md"
      - ".github/**"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  test:
    name: test
    uses: ./.github/workflows/run-tests.yml
    with:
      use_self_hosted_runners: false
